from models.cathedra import Cathedra
from models.facility import Facility
from models.professor import Professor
from models.user import User
from models.student import Student
from models.load_page import LoadPage
from models.load_page_work_type import LoadPageWorkType
from models.group import Group
from models.load_page_subtype import LoadPageSubtype